# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

profiles:
  copy-merged:
    storage_provider:
      type: gcs
      options:
        base_path: copy-merged
