# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

profiles:
  mayank-nemo-cc:
    storage_provider:
      type: gcs
      options:
        base_path: mayank-nemo-cc
