# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

profiles:
  data:
    storage_provider:
      type: gcs
      options:
        base_path: mayank-data
