# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

load_args:
  load_path: /u/shawntan/proj/mayank/checkpoints/hybrid-attn-mamba2-2.5b
  iteration: 5000

mixed_precision_args:
  # use this if you want to save the unsharded model in specific dtype,
  # if not specified, its taken from the training config in the saved checkpoint
  dtype: bf16

# where to save the HF safetensors checkpoint
unsharded_path: /u/shawntan/proj/mayank/checkpoints/hybrid-attn-mamba2-2.5b/unsharded_model
