# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

datasets:
  # class_name - data_name & data_sampling_ratio are not used but need to be passed to avoid errors
  - class_name: MegatronDataset
    data_name: Megatron
    data_sampling_ratio: 1
    class_args:
      eval_steps: 2
      data_cache_path: /u/shawntan/proj/mayank/data-cache
      # Option 1: data loading using --data-path with single file
      data_path:
        - 0.5
        - /proj/datasets/granite-4-datasets-megatron-merged/web-nemotron-cc-hq-p2_0
        - 0.5
        - /proj/datasets/granite-4-datasets-megatron-merged/web-nemotron-cc-hq-p2_1
      split: 99.5,0.5,0
      # split: 1,0,0
      sequence_length: 4096

tokenizer_args:
  tokenizer_name: /proj/checkpoints/dmf-lh-checkpoints/granite-4.0-tiktoken

kernel_args:
  kernels:
    - smoe
    - flash_attention_2

model_args:
  model_class: AutoModelForCausalLM
  pretrained_config:
    initializer_range: 0.1
    layer_norm_epsilon: 1e-05
    model_type: gpt_base
    normalization_function: rmsnorm
    position_embedding_type: rope
    hidden_size: 1536
    m_width: 6
    m_emb: 12
    m_residual: 0.22
    num_layers: 40
    init_method: mup
    router_aux_loss_coef: 0.01
    bos_token_id: 100257
    eos_token_id: 100257
    pad_token_id: 100256
    vocab_size: 100352
    max_position_embeddings: 4096
    sequence_mixer_blocks:
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 12
        num_key_value_heads: 12
        attention_multiplier: 0.015625
        add_bias: false
    mlp_blocks:
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
      - mlp_type: MoE
        activation_function: swiglu
        intermediate_size: 256
        num_experts: 128
        num_experts_per_tok: 8
        add_bias: false
  efficient_initialization: true

tuning_args:
  tuning_method: pretraining

save_args:
  save_path: /u/shawntan/proj/mayank/checkpoints/smoe
  save_interval: 5000

# load_args:
#   load_path: /mnt/vast/proj/checkpoints/mayank/moe-tc-1b

logging_args:
  log_interval: 10
  experiments_tracker_name: wandb
  wandb_args:
    project: fast-kernels
    name: smoe

training_parameters:
  num_training_steps: 250000
  eval_interval: 10000
  micro_batch_size: 6
  gradient_accumulation_steps: 3
  eval_during_training: true

optimizer_args:
  params_group_method: mup
  class_name: TorchAdamW
  class_args:
    lr: 0.01
    weight_decay: 0.1
    betas:
      - 0.9
      - 0.95
    eps: 1e-10

lr_scheduler_args:
  lr_decay_style: power
  num_warmup_steps: 2500
  num_constant_steps: 0
  num_decay_steps: 25000
  extra_lr_scheduler_args:
    # 4 * global_batch_size
    a: 4608
    # constant
    b: -0.51
    # global_batch_size in number of tokens
    c: 4718592

mixed_precision_args:
  dtype: bf16

distributed_args:
  stage: 3
  torch_compile: true
  zero_topology:
    data_parallel_sharding_world_size: 8
    data_parallel_replication_world_size: 8
